# Generated by Django 2.0.3 on 2018-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180418_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
